use CashDesc
insert into Actions(AccountNumber, ProductId, Amount) values
('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 1, 100),
('BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB', 2, 200),
('BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB', 3, 300)